version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: bun
    directory: /frontend
    schedule:
      interval: weekly
    groups:
      frontend:
        patterns:
          - "*"
