# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    default_locale: '%locale%'
    csrf_protection: ~
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: ~
        cookie_secure: auto
        cookie_samesite: lax

    #esi: true
    #fragments: true

    # Configure error and deprecation logging
    php_errors:
        log: true
        throw: false # don't throw exceptions for deprecations

    error_controller: null

    # Removed templating engines as it's deprecated
    # Use Twig directly instead
