framework:
    validation:
        email_validation_mode: html5
        enable_attributes: true
        # Prefer attributes/explicit mappings to avoid deprecated annotation reader
        auto_mapping:
            App\Entity\: []
