---
services:

  httpd:
    ports:
      - 8765:80
    volumes:
      - ./public:/var/www/html/public

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: devbox
    image: ghcr.io/netresearch/timetracker:devbox_v4
    volumes:
      - .:/var/www/html
      - ./public:/var/www/html/public
      - ./app/cache:/var/www/html/app/cache
      - ./app/logs:/var/www/html/app/logs
      - ./app/config/parameters.yml:/var/www/html/app/config/parameters.yml
      - /usr/local/share/ca-certificates/:/usr/local/share/ca-certificates/host

###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432"
###< doctrine/doctrine-bundle ###
