---
services:

  httpd:
    ports:
      - 8765:80
    volumes:
      - ./public:/var/www/html/public

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: devbox
    image: ghcr.io/netresearch/timetracker:devbox_v4
    volumes:
      - .:/var/www/html
      - /usr/local/share/ca-certificates/:/usr/local/share/ca-certificates/host
