version: '3.5'
services:

  httpd:
    image: nginx:alpine
    volumes:
      - app:/var/www/html
      - ./nginx-conf.d-default.conf:/etc/nginx/conf.d/default.conf
    links:
      - app:phpfpm
    restart: always

  app:
    build: .
    image: registry.netresearch.de/timetracker/timetracker
    volumes:
      - app:/var/www/html
#      - app-cache:/var/www/html/app/cache
#      - app-logs:/var/www/html/app/logs
      - ./app/config/parameters.ini:/var/www/html/app/config/parameters.ini
    links:
      - db:db
    restart: always

  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=global123
      - MYSQL_USER=global
      - MYSQL_PASSWORD=global
      - MYSQL_DATABASE=timetracker
    volumes:
      - db-data:/var/lib/mysql
    restart: always

networks:

  default:
    driver: "bridge"

volumes:

  app:
    driver: local

#  app-cache:
#    driver: local

#  app-logs:
#    driver: local

  db-data:
    driver: local

