version: '3.5'
services:

  app:
    build: .
    image: netresearch/timetracker
    volumes:
      - app-pub:/var/www/html/web
      - app-cache:/var/www/html/app/cache
      - app-logs:/var/www/html/app/logs
      - ./app/config/parameters.yml:/var/www/html/app/config/parameters.yml
    links:
      - db:db
    restart: always

  httpd:
    image: nginx:alpine
    volumes:
      - app-pub:/var/www/html/web
      - ./nginx-conf.d-default.conf:/etc/nginx/conf.d/default.conf
    links:
      - app:phpfpm
    restart: always

  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=global123
      - MYSQL_USER=global
      - MYSQL_PASSWORD=global
      - MYSQL_DATABASE=timetracker
    volumes:
      - db-data:/var/lib/mysql
    restart: always

networks:

  default:
    driver: "bridge"

volumes:

  app-pub:
    driver: local

  app-cache:
    driver: local

  app-logs:
    driver: local

  db-data:
    driver: local
