_start:
    path:  /
    defaults: { _controller: App\Controller\DefaultController::indexAction }

user_add:
    path: /user/add
    defaults: { _controller: App\Controller\AdminController::saveUserAction }

time_summary:
    path: /getTimeSummary
    defaults: { _controller: App\Controller\DefaultController::getTimeSummaryAction }

interpretation_activity:
    path: /interpretation/activity
    defaults: { _controller: App\Controller\InterpretationController::groupByActivityAction }

interpretation_time:
    path: /interpretation/time
    defaults: { _controller: App\Controller\InterpretationController::groupByWorktimeAction }

interpretation_customer:
    path: /interpretation/customer
    defaults: { _controller: App\Controller\InterpretationController::groupByCustomerAction }

interpretation_project:
    path: /interpretation/project
    defaults: { _controller: App\Controller\InterpretationController::groupByProjectAction }

interpretation_ticket:
    path: /interpretation/ticket
    defaults: { _controller: App\Controller\InterpretationController::groupByTicketAction }

interpretation_user:
    path: /interpretation/user
    defaults: { _controller: App\Controller\InterpretationController::groupByUserAction }

interpretation_entries:
    path: /interpretation/entries
    defaults: { _controller: App\Controller\InterpretationController::getLastEntriesAction }

interpretation_all_entries:
    path:  /interpretation/allEntries
    defaults: { _controller: App\Controller\InterpretationController::getAllEntriesAction }

timetracking_save:
    path: /tracking/save
    defaults: { _controller: App\Controller\CrudController::saveAction }

timetracking_delete:
    path: /tracking/delete
    defaults: { _controller: App\Controller\CrudController::deleteAction }

timetracking_bulkentry:
    path: /tracking/bulkentry
    defaults: { _controller: App\Controller\CrudController::bulkentryAction }

_getSummary:
    path: /getSummary
    defaults: { _controller: App\Controller\DefaultController::getSummaryAction }

_getData:
    path:  /getData
    defaults: { _controller: App\Controller\DefaultController::getDataAction }

_getDataDays:
    path:  /getData/days/{days}
    defaults: { _controller: App\Controller\DefaultController::getDataAction, days: 3 }
    requirements:
        days:  \d+

_getCustomers:
    path:  /getCustomers
    defaults: { _controller: App\Controller\DefaultController::getCustomersAction }

_getAllCustomers:
    path:  /getAllCustomers
    defaults: { _controller: App\Controller\AdminController::getCustomersAction }

_getCustomer:
    path:  /getCustomer
    defaults: { _controller: App\Controller\DefaultController::getCustomerAction }

_getAllTeams:
    path:  /getAllTeams
    defaults: { _controller: App\Controller\AdminController::getTeamsAction }

_getUsers:
    path:  /getUsers
    defaults: { _controller: App\Controller\DefaultController::getUsersAction }

_getAllUsers:
    path:  /getAllUsers
    defaults: { _controller: App\Controller\AdminController::getUsersAction }

_getProjects:
    path:  /getProjects
    defaults: { _controller: App\Controller\DefaultController::getProjectsAction }

_getAllProjects:
    path:  /getAllProjects
    defaults: { _controller: App\Controller\DefaultController::getAllProjectsAction }

_getProjectStructure:
    path:  /getProjectStructure
    defaults: { _controller: App\Controller\DefaultController::getProjectStructureAction }

_getActivities:
    path:  /getActivities
    defaults: { _controller: App\Controller\DefaultController::getActivitiesAction }

_getTicketSystems:
    path:  /getTicketSystems
    defaults: { _controller: App\Controller\AdminController::getTicketSystemsAction }

_getHolidays:
    path:  /getHolidays
    defaults: { _controller: App\Controller\DefaultController::getHolidaysAction }

_getAllPresets:
    path:  /getAllPresets
    defaults: { _controller: App\Controller\AdminController::getPresetsAction }

_getContracts:
    path:  /getContracts
    defaults: { _controller: App\Controller\AdminController::getContractsAction }

_getTicketTimeSummary:
    path: /getTicketTimeSummary/{ticket}
    defaults: { _controller: App\Controller\DefaultController::getTicketTimeSummaryAction, ticket: null }

_getTicketTimeSummaryJs:
    path: /scripts/timeSummaryForJira
    defaults: { _controller: App\Controller\DefaultController::getTicketTimeSummaryJsAction }

_login:
    path:  /login
    defaults: { _controller: App\Controller\DefaultController::loginAction }

_logout:
    path:  /logout
    defaults: { _controller: App\Controller\DefaultController::logoutAction }

_export:
    path: /export/{days}
    defaults: { _controller: App\Controller\DefaultController::exportAction, days: 10000 }
    requirements:
        days: \d+

_controllingExport:
    path: /controlling/export/{userid}/{year}/{month}/{project}/{customer}/{billable}
    defaults:
      _controller: App\Controller\ControllingController::exportAction
      userid: 0
      year: 0
      month: 0
      project: 0
      customer: 0
      billable: 0
    requirements: { year: \d+, userid: \d+}

check_status:
    path: /status/check
    defaults: { _controller: App\Controller\StatusController::checkAction }

check_page:
    path: /status/page
    defaults: { _controller: App\Controller\StatusController::pageAction }

status:
    path: /status
    defaults: { _controller: App\Controller\StatusController::pageAction }

saveProject:
    path: /project/save
    defaults: { _controller: App\Controller\AdminController::saveProjectAction }

deleteProject:
    path: /project/delete
    defaults: { _controller: App\Controller\AdminController::deleteProjectAction }

syncAllProjectSubtickets:
    path: /projects/syncsubtickets
    defaults: { _controller: App\Controller\AdminController::syncAllProjectSubticketsAction }

syncProjectSubtickets:
    path: /projects/{project}/syncsubtickets
    defaults: { _controller: App\Controller\AdminController::syncProjectSubticketsAction }

saveCustomer:
    path: /customer/save
    defaults: { _controller: App\Controller\AdminController::saveCustomerAction }

deleteCustomer:
    path: /customer/delete
    defaults: { _controller: App\Controller\AdminController::deleteCustomerAction }

saveUser:
    path: /user/save
    defaults: { _controller: App\Controller\AdminController::saveUserAction }

deleteUser:
    path: /user/delete
    defaults: { _controller: App\Controller\AdminController::deleteUserAction }

savePreset:
    path: /preset/save
    defaults: { _controller: App\Controller\AdminController::savePresetAction }

saveTicketSystem:
    path: /ticketsystem/save
    defaults: { _controller: App\Controller\AdminController::saveTicketSystemAction }

deleteTicketSystem:
    path: /ticketsystem/delete
    defaults: { _controller: App\Controller\AdminController::deleteTicketSystemAction }

deletePreset:
    path: /preset/delete
    defaults: { _controller: App\Controller\AdminController::deletePresetAction }

saveSettings:
    path: /settings/save
    defaults: { _controller: App\Controller\SettingsController::saveAction }

saveActivity:
    path: /activity/save
    defaults: { _controller: App\Controller\AdminController::saveActivityAction }

deleteActivity:
    path: /activity/delete
    defaults: { _controller: App\Controller\AdminController::deleteActivityAction }

saveTeam:
    path: /team/save
    defaults: { _controller: App\Controller\AdminController::saveTeamAction }

deleteTeam:
    path: /team/delete
    defaults: { _controller: App\Controller\AdminController::deleteTeamAction }

saveContract:
    path: /contract/save
    defaults: { _controller: App\Controller\AdminController::saveContractAction }

deleteContract:
    path: /contract/delete
    defaults: { _controller: App\Controller\AdminController::deleteContractAction }

jiraOAuthCallback:
    path: /jiraoauthcallback
    defaults: { _controller: App\Controller\DefaultController::jiraOAuthCallbackAction }

syncEntriesToJira:
    path: /syncentries/jira
    defaults: { _controller: App\Controller\DefaultController::syncEntriesToJiraAction }
