## migrated to attribute routes; legacy entries removed

## migrated to attribute routes in StatusController
check_status:
    path: /status/check
    defaults: { _controller: App\Controller\StatusController::checkAction }

check_page:
    path: /status/page
    defaults: { _controller: App\Controller\StatusController::pageAction }

saveProject:
    path: /project/save
    defaults: { _controller: App\Controller\AdminController::saveProjectAction }

deleteProject:
    path: /project/delete
    defaults: { _controller: App\Controller\AdminController::deleteProjectAction }

syncAllProjectSubtickets:
    path: /projects/syncsubtickets
    defaults: { _controller: App\Controller\AdminController::syncAllProjectSubticketsAction }

syncProjectSubtickets:
    path: /projects/{project}/syncsubtickets
    defaults: { _controller: App\Controller\AdminController::syncProjectSubticketsAction }

saveCustomer:
    path: /customer/save
    defaults: { _controller: App\Controller\AdminController::saveCustomerAction }

deleteCustomer:
    path: /customer/delete
    defaults: { _controller: App\Controller\AdminController::deleteCustomerAction }

saveUser:
    path: /user/save
    defaults: { _controller: App\Controller\AdminController::saveUserAction }

deleteUser:
    path: /user/delete
    defaults: { _controller: App\Controller\AdminController::deleteUserAction }

savePreset:
    path: /preset/save
    defaults: { _controller: App\Controller\AdminController::savePresetAction }

saveTicketSystem:
    path: /ticketsystem/save
    defaults: { _controller: App\Controller\AdminController::saveTicketSystemAction }

deleteTicketSystem:
    path: /ticketsystem/delete
    defaults: { _controller: App\Controller\AdminController::deleteTicketSystemAction }

deletePreset:
    path: /preset/delete
    defaults: { _controller: App\Controller\AdminController::deletePresetAction }

## migrated to attribute route in SettingsController::saveAction

saveActivity:
    path: /activity/save
    defaults: { _controller: App\Controller\AdminController::saveActivityAction }

deleteActivity:
    path: /activity/delete
    defaults: { _controller: App\Controller\AdminController::deleteActivityAction }

saveTeam:
    path: /team/save
    defaults: { _controller: App\Controller\AdminController::saveTeamAction }

deleteTeam:
    path: /team/delete
    defaults: { _controller: App\Controller\AdminController::deleteTeamAction }

saveContract:
    path: /contract/save
    defaults: { _controller: App\Controller\AdminController::saveContractAction }

deleteContract:
    path: /contract/delete
    defaults: { _controller: App\Controller\AdminController::deleteContractAction }

jiraOAuthCallback:
    path: /jiraoauthcallback
    defaults: { _controller: App\Controller\DefaultController::jiraOAuthCallbackAction }

syncEntriesToJira:
    path: /syncentries/jira
    defaults: { _controller: App\Controller\AdminController::jiraSyncEntriesAction }


