name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below.

        Before submitting, please search existing issues to avoid duplicates.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: TimeTracker Version
      description: What version of TimeTracker are you using?
      options:
        - 5.x (latest)
        - 4.x
        - Development (main branch)
        - Other
    validations:
      required: true

  - type: input
    id: php-version
    attributes:
      label: PHP Version
      description: What PHP version are you running?
      placeholder: "8.5.0"
    validations:
      required: false

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: What browser are you using? (if applicable)
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other
        - N/A (backend issue)
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Please paste any relevant log output (var/log/*.log)
      render: shell
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or information about the problem.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/netresearch/timetracker/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
