SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE `accounts`;
TRUNCATE TABLE `activities`;
TRUNCATE TABLE `contracts`;
TRUNCATE TABLE `entries`;
TRUNCATE TABLE `holidays`;
TRUNCATE TABLE `presets`;
TRUNCATE TABLE `projects`;
TRUNCATE TABLE `teams`;
TRUNCATE TABLE `teams_customers`;
TRUNCATE TABLE `teams_users`;
TRUNCATE TABLE `tickets`;
TRUNCATE TABLE `ticket_systems`;
TRUNCATE TABLE `users`;
TRUNCATE TABLE `users_ticket_systems`;
SET FOREIGN_KEY_CHECKS=1;
INSERT INTO `users` (`id`,`username`,`abbr`, `type`, `jira_token`, `show_empty_line`, `suggest_time`, `show_future`, `locale`) VALUES (1,'i.myself','UTT','PL',NULL,0,1,1,'de');
INSERT INTO `teams` (`id`,`name`,`lead_user_id`) VALUES (1,'Kuchenbäcker',1);
INSERT INTO `teams_users` (`id`, `team_id`, `user_id`) VALUES (1,1,1);
