# config/routes.yaml
# Main routing configuration

# Standard login route (Symfony 6 convention)
_login:
    path: /login
    controller: App\Controller\SecurityController::login

# Login check route for form_login
login_check:
    path: /login_check
    methods: POST

# Logout route (Symfony 6 convention)
_logout:
    path: /logout
    methods: GET

# Routes are primarily defined via PHP attributes (#[Route]) in controllers on Symfony 6.4
