# config/routes.yaml
# Main routing configuration

# Standard login route (Symfony 4 convention)
_login:
    path: /login
    controller: App\Controller\SecurityController::login

# Login check route for form_login
login_check:
    path: /login_check
    methods: POST

# Logout route (Symfony 4 convention)
_logout:
    path: /logout
    methods: GET

# TimeTracker routes - Load from the legacy bundle config for backward compatibility
timetracker:
    resource: "./legacy_bundle/routing.yml"

# Enable attribute routes for controllers
controllers:
    resource: '../src/Controller/'
    type: annotation
