# config/routes.yaml
# Main routing configuration

# Standard login route (Symfony 4 convention)
_login:
    path: /login
    controller: App\Controller\SecurityController::login

# Logout route (Symfony 4 convention)
_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

# TimeTracker routes - Load from the legacy bundle config for backward compatibility
timetracker:
    resource: "./legacy_bundle/routing.yml"
