# config/routes.yaml
# Main routing configuration

# Unified login route (Symfony 7.3 convention)
# Handles both GET (display form) and POST (authentication)
_login:
    path: /login
    controller: App\Controller\SecurityController::login
    methods: [GET, POST]

# Legacy login_check route for backward compatibility
# Will be removed after full migration
login_check:
    path: /login_check
    controller: App\Controller\SecurityController::login
    methods: POST

# Logout route (Symfony 7.3 convention)
_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout
    methods: GET

# Routes are primarily defined via PHP attributes (#[Route]) in controllers on Symfony 6.4
