# config/services_test.yaml
services:
    # Make services public in the test environment
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    # Define the TestClock service
    Tests\Service\TestClock: ~ # Autowiring should handle constructor

    # Alias ClockInterface to TestClock for the test environment
    App\Service\ClockInterface: '@Tests\Service\TestClock'

    # You might need to explicitly declare EntryRepository here if autowiring
    # doesn't pick up the test alias correctly, although it usually does.
    # App\Repository\EntryRepository:
    #     # Arguments will likely be autowired correctly, including the aliased ClockInterface
    #     # public: true # Ensure it's public if needed by other test services
