# config/services_test.yaml
services:
    # Make services public in the test environment
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    # Define the TestClock service
    Tests\Service\TestClock: ~ # Autowiring should handle constructor

    # Alias ClockInterface to TestClock for the test environment
    App\Service\ClockInterface: '@Tests\Service\TestClock'

    # Ensure EntryRepository is properly configured for tests with correct parameters
    App\Repository\EntryRepository:
        arguments:
            $registry: '@doctrine'
            $timeCalculationService: '@App\Service\Util\TimeCalculationService'
        tags:
            - { name: 'doctrine.repository_service' }
        public: true