#!/usr/bin/env python3
"""Add or verify the SPDX copyright header on this project's source files.

OpenSSF Best Practices Gold asks for a copyright and licence statement in every
source file (`copyright_per_file`, `license_per_file`). This script is both the
one-off tool that added the missing ones and the gate that keeps them there:
run without arguments it writes the header where it is missing, with --check it
reports the files that lack one and exits non-zero.

It never rewrites an existing header. Several files carry a different copyright
line — the 2018 notices from the original Netresearch GmbH & Co. KG code, and
the 2025-2026 range on files that predate the current year — and overwriting
those would erase history rather than add a licence statement.

Scope is source code we wrote. Configuration, data and vendored third-party
code are excluded; see EXCLUDED_PREFIXES and EXTENSIONS below.
"""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys

COPYRIGHT = "Copyright (c) 2026 Netresearch DTT GmbH"
LICENSE = "SPDX-License-Identifier: AGPL-3.0-only"
MARKER = "SPDX-License-Identifier"

# How the header is written per file type: (prefix, line prefix, suffix).
BLOCK = ("/*", " * ", " */")
HASH = (None, "# ", None)
# `-#}` strips the whitespace that follows the comment. Without it the two
# newlines after the header land in the rendered output, which is invisible in
# an HTML template and two empty leading lines in templates/export.csv.twig.
TWIG = ("{#", " # ", " -#}")

EXTENSIONS = {
    ".php": BLOCK,
    ".ts": BLOCK,
    ".tsx": BLOCK,
    ".js": BLOCK,
    ".jsx": BLOCK,
    ".mjs": BLOCK,
    ".cjs": BLOCK,
    ".css": BLOCK,
    ".scss": BLOCK,
    ".sh": HASH,
    ".twig": TWIG,
}

# Not ours, or not written by hand.
EXCLUDED_PREFIXES = (
    "public/docs/swagger/",  # vendored Swagger UI distribution
    "vendor/",
    "node_modules/",
)
EXCLUDED_FILES = (
    "config/reference.php",  # generated by Symfony, overwritten on every run
)

SHEBANG = re.compile(r"^#!.*\n")
PHP_OPEN = re.compile(r"^<\?php[ \t]*\n")


def tracked_files() -> list[str]:
    out = subprocess.run(
        ["git", "ls-files"], capture_output=True, text=True, check=True
    ).stdout
    return out.splitlines()


def in_scope(path: str) -> bool:
    if path in EXCLUDED_FILES:
        return False
    if path.startswith(EXCLUDED_PREFIXES):
        return False
    return os.path.splitext(path)[1] in EXTENSIONS


def render(style: tuple[str | None, str, str | None]) -> str:
    open_, line, close = style
    parts = []
    if open_:
        parts.append(open_)
    parts.append(f"{line}{COPYRIGHT}".rstrip())
    parts.append(f"{line}{LICENSE}".rstrip())
    if close:
        parts.append(close)
    return "\n".join(parts) + "\n"


def insert(path: str, text: str) -> str:
    """Return `text` with the header inserted at the right place for its type."""
    header = render(EXTENSIONS[os.path.splitext(path)[1]])

    match = PHP_OPEN.match(text)
    if match:  # after `<?php`, before `declare(strict_types=1)`
        return f"{match.group(0)}\n{header}\n{text[match.end():].lstrip(chr(10))}"

    match = SHEBANG.match(text)
    if match:  # after the shebang, which must stay on line 1
        return f"{match.group(0)}\n{header}\n{text[match.end():].lstrip(chr(10))}"

    return f"{header}\n{text}"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="report files without a header and exit 1; write nothing",
    )
    args = parser.parse_args()

    missing = []
    for path in tracked_files():
        if not in_scope(path):
            continue
        with open(path, encoding="utf-8") as handle:
            text = handle.read()
        if MARKER in text[:2000]:
            continue
        missing.append(path)
        if not args.check:
            with open(path, "w", encoding="utf-8") as handle:
                handle.write(insert(path, text))

    if args.check:
        if missing:
            print(f"{len(missing)} file(s) without an SPDX header:", file=sys.stderr)
            for path in missing:
                print(f"  {path}", file=sys.stderr)
            print(
                "\nRun `python3 scripts/spdx-headers.py` to add them.", file=sys.stderr
            )
            return 1
        print("Every source file in scope carries an SPDX header.")
        return 0

    print(f"Added a header to {len(missing)} file(s).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
