resources:
- name: timetracker-docker-image-tag
  type: docker-image
  source:
    repository: registry.netresearch.de/timetracker/timetracker
    username: {{GITLAB_NETRESEARCH_USER}}
    password: {{GITLAB_NETRESEARCH_USER_TOKEN}}
- name: timetracker-git-sources
  type: git
  source:
    uri:  git@github.com:netresearch/timetracker.git
    branch: utility2
    private_key: {{GITHUB_COM_KEY}}
jobs:
- name: timetracker-build
  plan:
  - aggregate:
    - get: timetracker-git-sources
      trigger: true
      params:
        depth: 1
  - put: timetracker-docker-image-tag
    params:
      build: timetracker-git-sources
      tag: timetracker-git-sources/ci/tags/latest
    get_params:
      skip_download: true

